# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjMxYjk2ZjNiNTk4ODFjNzk1MTEyMzllZmYzNmMyMDg0ODNjOTVmYTFiYWY5MWUwYTQ1ODgyMzcxZTAyNGIzOTkwMGYxYjcwNGUwODEzOGZmMDk4OGMxYzFiNTk3NDQwNWE2NjI2NzIwMzE0MDJmNTEwNDU2NzRkMmFiNDg5NDA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
